title: Mila Beauty Room
description: Авторские стрижки и окрашивание волос — Mila Beauty Room, София
url: https://mila-room.beauty
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
